%%---------------------------------------------------------
% Author       : LYC
% Date         : 2020-06-09 15:50:13
% LastEditTime : 2020-07-14 14:59:37
% LastEditors  : LYC
% Description  :
% FilePath     : /code/home/liuyc/lib/tools/matlab/myTools/a_rschingFun/Observe/obsPlotParameters.m
%
%%---------------------------------------------------------
function [mlabels, areaNum] = obsPlotParameters(p_1, p_2, p_3)
    % By liuyincheng (ycliu@smail.nju.edu.cn)
    % purpose: auto output plot parameters, so we only need to modify once if something change.
    % eg:[mlabels, areaNum] = plotParameters('toa', 'land','cld-clr')
    %
    % p_1: input, determine 'SFC', 'TOA', 'ATM(TOA-SFC)'
    % p_2: input, determine 'landSea' or 'land','china'
    % p_3: input, determine 'ERA5-radEffect-tsRad','ERA5-radEffect-ts','ERAi' or 'CERES','MODIS'
    %% commom labels
    level_label = {'SFC', 'TOA', 'ATM(TOA-SFC)'}; % plot which level to plot
    dataname = {'ERA5', 'ERAi', 'CERES', 'MODIS'};

    mlabels.month = {'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'};
    mlabels.season = {'MAM', 'JJA', 'SON', 'DJF'};
    unitRad = ' $\left( W\cdot m^{-2}/10a \right) $';

    if strcmp(p_3, 'ERA5-radEffect-tsRad') == 1 || strcmp(p_3, 'era5-radEffect-tsRad') == 1
        mlabels.dataName = {'ERA5'};
        if mean(p_1 == 1) == 1 || strcmp(p_1, 'SFC') == 1 || strcmp(p_1, 'sfc') == 1
            p_1 = 1;
            mlabels.unite = {unitRad, unitRad, unitRad, ...
                unitRad, unitRad, unitRad, ...
                unitRad, unitRad, unitRad};
            mlabels.component = {'Ts radEffect', 'RHeating include LH+SH', 'RHeating(sfc)', ...
                'Ta radEffect', 'Cloud radEffect', 'q radEffect', ...
                'albedo radEffect', 'Ta+q+Alb+Cloud radEffect', 'Kernel Residual'};
            mlabels.componentNames = {'dRsfc_ts', 'drhsPlus', 'drhs' ...
                'dRsfc_ta', 'dRsfc_cloud', 'dRsfc_q', ...
                'dRsfc_alb', 'dRsfc_mainEffect', 'dRsfc_residual'};

        elseif mean(p_1 == 2) == 1 || strcmp(p_1, 'TOA') == 1 || strcmp(p_1, 'toa') == 1
            p_1 = 2;
            mlabels.unite = {unitRad, unitRad, ' (K/10a)', ...
                unitRad, unitRad, unitRad, ...
                unitRad, unitRad, unitRad};
            mlabels.component = {'TOA net radEffect', 'Ts radEffect', 'Ts', ...
                'Ta radEffect', 'Cloud radEffect', 'q radEffect', ...
                'albedo radEffect', 'Ta+q+Alb+Cloud radEffect', 'Kernel Residual'};
            mlabels.componentNames = {'dnetTOA', 'dRtoa_ts', 'dts' ...
                'dRtoa_ta', 'dRtoa_cloud', 'dRtoa_q', ...
                'dRtoa_alb', 'dRtoa_mainEffect', 'dRtoa_residual'};
        end

    elseif strcmp(p_3, 'ERA5-radEffect-ts') == 1 || strcmp(p_3, 'era5-radEffect-ts') == 1
        mlabels.dataName = {'ERA5'};
        if mean(p_1 == 1) == 1 || strcmp(p_1, 'SFC') == 1 || strcmp(p_1, 'sfc') == 1
            p_1 = 1;
            mlabels.unite = {' (K/10a)', unitRad, unitRad, ...
                unitRad, unitRad, unitRad, ...
                unitRad, unitRad, unitRad};
            mlabels.component = {'Ts', 'RHeating include LH+SH', 'RHeating(sfc)', ...
                'Ta radEffect', 'Cloud radEffect', 'q radEffect', ...
                'albedo radEffect', 'Ta+q+Alb+Cloud radEffect', 'Kernel Residual'};
            mlabels.componentNames = {'dts', 'drhsPlus', 'drhs' ...
                'dRsfc_ta', 'dRsfc_cloud', 'dRsfc_q', ...
                'dRsfc_alb', 'dRsfc_mainEffect', 'dRsfc_residual'};
        end

    elseif strcmp(p_3, 'ERAi-radEffect-tsRad') == 1 || strcmp(p_3, 'erai-radEffect-tsRad') == 1
        mlabels.dataName = {'ERAi'};
        if mean(p_1 == 1) == 1 || strcmp(p_1, 'SFC') == 1 || strcmp(p_1, 'sfc') == 1
            p_1 = 1;
            mlabels.unite = {unitRad, unitRad, unitRad, ...
                unitRad, unitRad, unitRad, ...
                unitRad, unitRad, unitRad};
            mlabels.component = {'Ts radEffect', 'RHeating include LH+SH', 'RHeating(sfc)', ...
                'Ta radEffect', 'Cloud radEffect', 'q radEffect', ...
                'albedo radEffect', 'Ta+q+Alb+Cloud radEffect', 'Kernel Residual'};
            mlabels.componentNames = {'dRsfc_ts', 'drhsPlus', 'drhs' ...
                'dRsfc_ta', 'dRsfc_cloud', 'dRsfc_q', ...
                'dRsfc_alb', 'dRsfc_mainEffect', 'dRsfc_residual'};

        elseif mean(p_1 == 2) == 1 || strcmp(p_1, 'TOA') == 1 || strcmp(p_1, 'toa') == 1
            p_1 = 2;
            mlabels.unite = {unitRad, unitRad, ' (K/10a)', ...
                unitRad, unitRad, unitRad, ...
                unitRad, unitRad, unitRad};
            mlabels.component = {'TOA net radEffect', 'Ts radEffect', 'Ts', ...
                'Ta radEffect', 'Cloud radEffect', 'q radEffect', ...
                'albedo radEffect', 'Ta+q+Alb+Cloud radEffect', 'Kernel Residual'};
            mlabels.componentNames = {'dnetTOA', 'dRtoa_ts', 'dts' ...
                'dRtoa_ta', 'dRtoa_cloud', 'dRtoa_q', ...
                'dRtoa_alb', 'dRtoa_mainEffect', 'dRtoa_residual'};
        end

    elseif strcmp(p_3, 'ERAi-radEffect-ts') == 1 || strcmp(p_3, 'erai-radEffect-ts') == 1
        mlabels.dataName = {'ERAi'};
        if mean(p_1 == 1) == 1 || strcmp(p_1, 'SFC') == 1 || strcmp(p_1, 'sfc') == 1
            p_1 = 1;
            mlabels.unite = {' (K/10a)', unitRad, unitRad, ...
                unitRad, unitRad, unitRad, ...
                unitRad, unitRad, unitRad};
            mlabels.component = {'Ts', 'RHeating include LH+SH', 'RHeating(sfc)', ...
                'Ta radEffect', 'Cloud radEffect', 'q radEffect', ...
                'albedo radEffect', 'Ta+q+Alb+Cloud radEffect', 'Kernel Residual'};
            mlabels.componentNames = {'dts', 'drhsPlus', 'drhs' ...
                'dRsfc_ta', 'dRsfc_cloud', 'dRsfc_q', ...
                'dRsfc_alb', 'dRsfc_mainEffect', 'dRsfc_residual'};
        end

    elseif strcmp(p_3, 'CERESCloud-ERA5-radEffect-tsRad_t') == 1 || strcmp(p_3, 'ceresCloud-era5-radEffect-tsRad_t') == 1
        mlabels.dataName = {'ERA5', 'CERES_t'};
        if mean(p_1 == 1) == 1 || strcmp(p_1, 'SFC') == 1 || strcmp(p_1, 'sfc') == 1
            p_1 = 1;
            mlabels.unite = {unitRad, unitRad, unitRad, ...
                unitRad, unitRad, unitRad, ...
                unitRad, unitRad, unitRad};
            mlabels.component = {'Ts radEffect', 'RHeating include LH+SH(CERES Rheating)', 'RHeating(CERES)', ...
                'Ta radEffect', 'Cloud radEffect(CERES)', 'q radEffect', ...
                'albedo radEffect', 'Ta+q+Alb+Cloud radEffect', 'Kernel Residual'};
            mlabels.componentNames = {'dRsfc_ts', 'dCErhsPlus_era5', 'dCErhs' ...
                'dRsfc_ta', 'dCEcloud_sfc_t', 'dRsfc_q', ...
                'dRsfc_alb', 'dCEmainEff_sfc_t', 'dCEres_sfc_t'};

        elseif mean(p_1 == 2) == 1 || strcmp(p_1, 'TOA') == 1 || strcmp(p_1, 'toa') == 1
            p_1 = 2;
            mlabels.unite = {unitRad, unitRad, ' (K/10a)', ...
                unitRad, unitRad, unitRad, ...
                unitRad, unitRad, unitRad};
            mlabels.component = {'TOA net radEffect(CERES)', 'Ts radEffect', 'Ts', ...
                'Ta radEffect', 'Cloud radEffect(CERES)', 'q radEffect', ...
                'albedo radEffect', 'Ta+q+Alb+Cloud radEffect', 'Kernel Residual'};
            mlabels.componentNames = {'dCEnetTOA', 'dRtoa_ts', 'dts' ...
                'dRtoa_ta', 'dCEcloud_toa_t', 'dRtoa_q', ...
                'dRtoa_alb', 'dCEmainEff_toa_t', 'dCEres_toa_t'};
        end

    elseif strcmp(p_3, 'CERESCloud-ERA5-radEffect-tsRad_c') == 1 || strcmp(p_3, 'ceresCloud-era5-radEffect-tsRad_c') == 1
        mlabels.dataName = {'ERA5', 'CERES_c'};
        if mean(p_1 == 1) == 1 || strcmp(p_1, 'SFC') == 1 || strcmp(p_1, 'sfc') == 1
            p_1 = 1;
            mlabels.unite = {unitRad, unitRad, unitRad, ...
                unitRad, unitRad, unitRad, ...
                unitRad, unitRad, unitRad};
            mlabels.component = {'Ts radEffect', 'RHeating include LH+SH(CERES Rheating)', 'RHeating(CERES)', ...
                'Ta radEffect', 'Cloud radEffect(CERES)', 'q radEffect', ...
                'albedo radEffect', 'Ta+q+Alb+Cloud radEffect', 'Kernel Residual'};
            mlabels.componentNames = {'dRsfc_ts', 'dCErhsPlus_era5', 'dCErhs' ...
                'dRsfc_ta', 'dCEcloud_sfc_c', 'dRsfc_q', ...
                'dRsfc_alb', 'dCEmainEff_sfc_c', 'dCEres_sfc_c'};

        elseif mean(p_1 == 2) == 1 || strcmp(p_1, 'TOA') == 1 || strcmp(p_1, 'toa') == 1
            p_1 = 2;
            mlabels.unite = {unitRad, unitRad, ' (K/10a)', ...
                unitRad, unitRad, unitRad, ...
                unitRad, unitRad, unitRad};
            mlabels.component = {'TOA net radEffect(CERES)', 'Ts radEffect', 'Ts', ...
                'Ta radEffect', 'Cloud radEffect(CERES)', 'q radEffect', ...
                'albedo radEffect', 'Ta+q+Alb+Cloud radEffect', 'Kernel Residual'};
            mlabels.componentNames = {'dCEnetTOA', 'dRtoa_ts', 'dts' ...
                'dRtoa_ta', 'dCEcloud_toa_c', 'dRtoa_q', ...
                'dRtoa_alb', 'dCEmainEff_toa_c', 'dCEres_toa_c'};
        end

    elseif strcmp(p_3, 'CERESCloud-ERAi-radEffect-tsRad_t') == 1 || strcmp(p_3, 'ceresCloud-erai-radEffect-tsRad_t') == 1
        mlabels.dataName = {'ERAi', 'CERES_t'};
        if mean(p_1 == 1) == 1 || strcmp(p_1, 'SFC') == 1 || strcmp(p_1, 'sfc') == 1
            p_1 = 1;
            mlabels.unite = {unitRad, unitRad, unitRad, ...
                unitRad, unitRad, unitRad, ...
                unitRad, unitRad, unitRad};
            mlabels.component = {'Ts radEffect', 'RHeating include LH+SH(CERES Rheating)', 'RHeating(CERES)', ...
                'Ta radEffect', 'Cloud radEffect(CERES)', 'q radEffect', ...
                'albedo radEffect', 'Ta+q+Alb+Cloud radEffect', 'Kernel Residual'};
            mlabels.componentNames = {'dRsfc_ts', 'dCErhsPlus_erai', 'dCErhs' ...
                'dRsfc_ta', 'dCEcloud_sfc_t', 'dRsfc_q', ...
                'dRsfc_alb', 'dCEmainEff_sfc_t', 'dCEres_sfc_t'};

        elseif mean(p_1 == 2) == 1 || strcmp(p_1, 'TOA') == 1 || strcmp(p_1, 'toa') == 1
            p_1 = 2;
            mlabels.unite = {unitRad, unitRad, ' (K/10a)', ...
                unitRad, unitRad, unitRad, ...
                unitRad, unitRad, unitRad};
            mlabels.component = {'TOA net radEffect(CERES)', 'Ts radEffect', 'Ts', ...
                'Ta radEffect', 'Cloud radEffect(CERES)', 'q radEffect', ...
                'albedo radEffect', 'Ta+q+Alb+Cloud radEffect', 'Kernel Residual'};
            mlabels.componentNames = {'dCEnetTOA', 'dRtoa_ts', 'dts' ...
                'dRtoa_ta', 'dCEcloud_toa_t', 'dRtoa_q', ...
                'dRtoa_alb', 'dCEmainEff_toa_t', 'dCEres_toa_t'};
        end

    elseif strcmp(p_3, 'CERESCloud-ERAi-radEffect-tsRad_c') == 1 || strcmp(p_3, 'ceresCloud-erai-radEffect-tsRad_c') == 1
        mlabels.dataName = {'ERAi', 'CERES_c'};
        if mean(p_1 == 1) == 1 || strcmp(p_1, 'SFC') == 1 || strcmp(p_1, 'sfc') == 1
            p_1 = 1;
            mlabels.unite = {unitRad, unitRad, unitRad, ...
                unitRad, unitRad, unitRad, ...
                unitRad, unitRad, unitRad};
            mlabels.component = {'Ts radEffect', 'RHeating include LH+SH(CERES Rheating)', 'RHeating(CERES)', ...
                'Ta radEffect', 'Cloud radEffect(CERES)', 'q radEffect', ...
                'albedo radEffect', 'Ta+q+Alb+Cloud radEffect', 'Kernel Residual'};
            mlabels.componentNames = {'dRsfc_ts', 'dCErhsPlus_erai', 'dCErhs' ...
                'dRsfc_ta', 'dCEcloud_sfc_c', 'dRsfc_q', ...
                'dRsfc_alb', 'dCEmainEff_sfc_c', 'dCEres_sfc_c'};

        elseif mean(p_1 == 2) == 1 || strcmp(p_1, 'TOA') == 1 || strcmp(p_1, 'toa') == 1
            p_1 = 2;
            mlabels.unite = {unitRad, unitRad, ' (K/10a)', ...
                unitRad, unitRad, unitRad, ...
                unitRad, unitRad, unitRad};
            mlabels.component = {'TOA net radEffect(CERES)', 'Ts radEffect', 'Ts', ...
                'Ta radEffect', 'Cloud radEffect(CERES)', 'q radEffect', ...
                'albedo radEffect', 'Ta+q+Alb+Cloud radEffect', 'Kernel Residual'};
            mlabels.componentNames = {'dCEnetTOA', 'dRtoa_ts', 'dts' ...
                'dRtoa_ta', 'dCEcloud_toa_c', 'dRtoa_q', ...
                'dRtoa_alb', 'dCEmainEff_toa_c', 'dCEres_toa_c'};
        end
    elseif strcmp(p_3, 'MODISCloud-ERA5-radEffect-tsRad') == 1 || strcmp(p_3, 'modiscloud-ear5-radEffect-tsRad') == 1
        mlabels.dataName = {'ERA5', 'MODIS'};
        if mean(p_1 == 1) == 1 || strcmp(p_1, 'SFC') == 1 || strcmp(p_1, 'sfc') == 1
            p_1 = 1;
            mlabels.unite = {unitRad, unitRad, unitRad, ...
                unitRad, unitRad, unitRad, ...
                unitRad, unitRad, unitRad};
            mlabels.component = {'Ts radEffect', 'RHeating include LH+SH', 'RHeating', ...
                'Ta radEffect', 'Cloud radEffect(MODIS)', 'q radEffect', ...
                'albedo radEffect', 'Ta+q+Alb+Cloud radEffect', 'Kernel Residual'};
            mlabels.componentNames = {'dRsfc_ts', 'drhsPlus', 'drhs' ...
                'dRsfc_ta', 'dRMOsfc_cloud', 'dRsfc_q', ...
                'dRsfc_alb', 'dRMO_mainEffect_sfc', 'dRMO_res_sfc'};
        end
    elseif strcmp(p_3, 'MODISCloud-ERAi-radEffect-tsRad') == 1 || strcmp(p_3, 'modiscloud-eari-radEffect-tsRad') == 1
        mlabels.dataName = {'ERAi', 'MODIS'};
        if mean(p_1 == 1) == 1 || strcmp(p_1, 'SFC') == 1 || strcmp(p_1, 'sfc') == 1
            p_1 = 1;
            mlabels.unite = {unitRad, unitRad, unitRad, ...
                unitRad, unitRad, unitRad, ...
                unitRad, unitRad, unitRad};
            mlabels.component = {'Ts radEffect', 'RHeating include LH+SH', 'RHeating', ...
                'Ta radEffect', 'Cloud radEffect(MODIS)', 'q radEffect', ...
                'albedo radEffect', 'Ta+q+Alb+Cloud radEffect', 'Kernel Residual'};
            mlabels.componentNames = {'dRsfc_ts', 'drhsPlus', 'drhs' ...
                'dRsfc_ta', 'dRMOsfc_cloud', 'dRsfc_q', ...
                'dRsfc_alb', 'dRMO_mainEffect_sfc', 'dRMO_res_sfc'};
        end
    end

    mlabels.vars = strcat('trendyr_', mlabels.componentNames);
    mlabels.level = level_label{p_1};

    if mean(p_2 == 0) == 1 || strcmp(p_2, 'land sea') == 1 || strcmp(p_2, 'landSea') == 1 || strcmp(p_2, 'landsea') == 1
        areaNum = 0;
        mlabels.area = 'landSea';
    elseif mean(p_2 == 1) == 1 || strcmp(p_2, 'land') == 1
        areaNum = 1;
        mlabels.area = 'land';
    elseif mean(p_2 == 2) == 1 || strcmp(p_2, 'china') == 1
        areaNum = 2;
        mlabels.area = 'china';
    end

end
