function [mlabels, areaNum] = plotParameters(p_1, p_2, p_3)
    % By liuyincheng (ycliu@smail.nju.edu.cn)
    % purpose: auto output plot parameters, so we only need to modify once if something change.
    % eg:[mlabels, areaNum] = plotParameters('toa', 'land','cld-clr')
    %
    % p_1: input, determine 'SFC', 'TOA', 'ATM(TOA-SFC)'
    % p_2: input, determine 'landSea' or 'land','china'
    % p_3: input, determine 'clr-cld' , 'cld-clr', 'cldKernels'

    %% commom labels
    level_label = {'SFC', 'TOA', 'ATM(TOA-SFC)'}; % plot which level to plot

    mlabels.month = {'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'};
    mlabels.season = {'MAM', 'JJA', 'SON', 'DJF'};
    mlabels.algmPath = strcat('y_cloudCal_', p_3);

    if mean(p_1 == 2)==1 || strcmp(p_1, 'TOA') == 1 || strcmp(p_1, 'toa') == 1
        if strcmp(p_3, 'cld-clr_nodp') == 0
            p_1 = 2;
            %% specific labels
            mlabels.unite = {' trend(W\cdotm-2/10a)', ' trend(W\cdotm-2/10a)', ' trend(W\cdotm-2/10a)', ...
                ' trend(W\cdotm-2/10a)', ' trend(W\cdotm-2/10a)', ' trend(W\cdotm-2/10a)', ...
                ' trend(W\cdotm-2/10a)', ' trend(W\cdotm-2/10a)', ' trend(W\cdotm-2/10a)', ...
                ' trend(W\cdotm-2/10a)', ' trend(W\cdotm-2/10a)', ' trend(W\cdotm-2/10a)'};
            mlabels.component = {'Ts radEffect', 'TOA net Flux', 'RHeating(sfc)', ...
                'Ta Effect', 'Ta Effect(near sfc)', 'Ta Effect(without near sfc) ', ...
                'Ts Effect on atmos', 'Ta+q+Alb+Cloud Effect', 'Kernel Residual', ...
                'Cloud Effect', 'q Effect', 'Albedo Effect'}; %4*3
            mlabels.componentNames = {'dRtoa_ts', 'dnetTOA', 'drhs', ...
                'dRtoa_ta', 'dRtoa_tas2', 'dRtoa_taOnly2', ...
                'dRatm_tsAtom', 'dRtoa_mainEffect', 'dRtoa_residual', ...
                'dRtoa_cloud', 'dRtoa_q', 'dRtoa_alb', 'dRtoa_ts'};
            mlabels.vars = strcat('trendyr_', mlabels.componentNames);
            mlabels.level = level_label{p_1};
        elseif strcmp(p_3, 'cld-clr_nodp') == 1
            p_1 = 2;
            %% specific labels
            mlabels.unite = {' trend(W\cdotm-2/10a)', ' trend(W\cdotm-2/10a)', ' trend(W\cdotm-2/10a)', ...
                ' trend(W\cdotm-2/10a)', ' trend(W\cdotm-2/10a)', ' trend(W\cdotm-2/10a)', ...
                ' trend(W\cdotm-2/10a)', ' trend(W\cdotm-2/10a)', ' trend(W\cdotm-2/10a)', ...
                ' trend(W\cdotm-2/10a)', ' trend(W\cdotm-2/10a)', ' trend(W\cdotm-2/10a)'};
            mlabels.component = {'Ts radEffect', 'TOA net Flux', 'RHeating(sfc)', ...
                'Ta Effect', 'Ts radEffect', 'Ts radEffect ', ...
                'Ts Effect on atmos', 'Ta+q+Alb+Cloud Effect', 'Kernel Residual', ...
                'Cloud Effect', 'q Effect', 'Albedo Effect'}; %4*3
            mlabels.componentNames = {'dRtoa_ts', 'dnetTOA', 'drhs', ...
                'dRtoa_ta', 'dRtoa_ts', 'dRtoa_ts', ...
                'dRatm_tsAtom', 'dRtoa_mainEffect', 'dRtoa_residual', ...
                'dRtoa_cloud', 'dRtoa_q', 'dRtoa_alb', 'dRtoa_ts'};
            mlabels.vars = strcat('trendyr_', mlabels.componentNames);
            mlabels.level = level_label{p_1};
        end
    elseif  mean(p_1 == 1)==1 || strcmp(p_1, 'SFC') == 1 || strcmp(p_1, 'sfc') == 1
        p_1 = 1;
        %% specific labels
        mlabels.unite = {' trend(W\cdotm-2/10a)', ' trend(W\cdotm-2/10a)', ' trend(W\cdotm-2/10a)', ...
            ' trend(W\cdotm-2/10a)', ' trend(W\cdotm-2/10a)', ' trend(W\cdotm-2/10a)', ...
            ' trend(W\cdotm-2/10a)', ' trend(W\cdotm-2/10a)', ' trend(W\cdotm-2/10a)', ...
            ' trend(W\cdotm-2/10a)', ' trend(W\cdotm-2/10a)', ' trend(W\cdotm-2/10a)'};
        mlabels.component = {'Ts radEffect', 'RHeating include LH+SH', 'RHeating(sfc)', ...
            'Ta Effect', 'Ta Effect(near sfc)', 'Ta Effect(without near sfc) ', ...
            'Ts Effect on atmos', 'Ta+q+Alb+Cloud Effect', 'Kernel Residual', ...
            'Cloud Effect', 'q Effect', 'Albedo Effect'}; %4*3
        mlabels.componentNames = {'dRsfc_ts',  'drhsPlus', 'drhs', ...
            'dRsfc_ta', 'dRsfc_tas2', 'dRsfc_taOnly2', ...
            'dRatm_tsAtom', 'dRsfc_mainEffect', 'dRsfc_residual', ...
            'dRsfc_cloud', 'dRsfc_q', 'dRsfc_alb', 'dRsfc_ts'};
        mlabels.vars = strcat('trendyr_', mlabels.componentNames);
        mlabels.level = level_label{p_1};
    end

    if mean(p_2 == 0)==1 || strcmp(p_2, 'land sea') == 1 || strcmp(p_2, 'landSea') == 1 || strcmp(p_2, 'landsea') == 1
        areaNum = 0;
        mlabels.area = 'landSea';
    elseif mean(p_2 == 1)==1 || strcmp(p_2, 'land') == 1
        areaNum = 1;
        mlabels.area = 'land';
    elseif mean(p_2 == 2)==1 || strcmp(p_2, 'china') == 1
        areaNum = 2;
        mlabels.area = 'china';
    end

    mlabels.fileN1 = strcat(mlabels.area, '_', p_3);

end
