%%---------------------------------------------------------
% Author       : LYC
% Date         : 2020-06-09 15:50:13
% LastEditTime : 2020-06-18 14:17:29
% LastEditors  : LYC
% Description  :
% FilePath     : /code/home/liuyc/lib/tools/matlab/myTools/a_rschingFun/plotParameters.m
%
%%---------------------------------------------------------
function [mlabels, areaNum] = plotParameters(p_1, p_2, p_3)
    % By liuyincheng (ycliu@smail.nju.edu.cn)
    % purpose: auto output plot parameters, so we only need to modify once if something change.
    % eg:[mlabels, areaNum] = plotParameters('toa', 'land','radEffect')
    %
    % p_1: input, determine 'SFC', 'TOA', 'ATM(TOA-SFC)'
    % p_2: input, determine 'landSea' or 'land','china'
    % p_3: input, determine  'radEffect', 'nonLocalCld_rad','nonLocalCld_Ts','nonLocalCld2'

    %% commom labels
    level_label = {'SFC', 'TOA', 'ATM(TOA-SFC)'}; % plot which level to plot

    mlabels.month = {'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'};
    mlabels.season = {'MAM', 'JJA', 'SON', 'DJF'};
    mlabels.algmPath = strcat('y_cloudCal_', p_3);

    if mean(p_1 == 2) == 1 || strcmp(p_1, 'TOA') == 1 || strcmp(p_1, 'toa') == 1

        if strcmp(p_3, 'radEffect') == 1
            p_1 = 2;
            %% specific labels
            mlabels.unite = {' trend$\left( W\cdot m^{-2}/10a \right) $', ' trend$\left( W\cdot m^{-2}/10a \right) $', ' trend$\left( W\cdot m^{-2}/10a \right) $', ...
                ' trend$\left( W\cdot m^{-2}/10a \right) $', ' trend$\left( W\cdot m^{-2}/10a \right) $', ' trend$\left( W\cdot m^{-2}/10a \right) $', ...
                ' trend$\left( W\cdot m^{-2}/10a \right) $', ' trend$\left( W\cdot m^{-2}/10a \right) $', ' trend$\left( W\cdot m^{-2}/10a \right) $', ...
                ' trend$\left( W\cdot m^{-2}/10a \right) $', ' trend$\left( W\cdot m^{-2}/10a \right) $', ' trend$\left( W\cdot m^{-2}/10a \right) $'};
            mlabels.component = {'Ts radEffect', 'TOA net Flux', 'RHeating(sfc)', ...
                'Ta radEffect', 'Ta radEffect(near sfc)', 'Ta radEffect(without near sfc) ', ...
                'Ts Effect on atmos', 'Ta+q+Alb+Cloud radEffect', 'Kernel Residual', ...
                'Cloud radEffect', 'q radEffect', 'Albedo radEffect'}; %4*3
            mlabels.componentNames = {'dRtoa_ts', 'dnetTOA', 'drhs', ...
                'dRtoa_ta', 'dRtoa_tas2', 'dRtoa_taOnly2', ...
                'dRatm_tsAtom', 'dRtoa_mainEffect', 'dRtoa_residual', ...
                'dRtoa_cloud', 'dRtoa_q', 'dRtoa_alb', 'dRtoa_ts'};
            mlabels.vars = strcat('trendyr_', mlabels.componentNames);
            mlabels.level = level_label{p_1};
        elseif strcmp(p_3, 'radEffect_nodp') == 1
            p_1 = 2;
            %% specific labels
            mlabels.unite = {' trend$\left( W\cdot m^{-2}/10a \right) $', ' trend$\left( W\cdot m^{-2}/10a \right) $', ' trend$\left( W\cdot m^{-2}/10a \right) $', ...
                ' trend$\left( W\cdot m^{-2}/10a \right) $', ' trend$\left( W\cdot m^{-2}/10a \right) $', ' trend$\left( W\cdot m^{-2}/10a \right) $', ...
                ' trend$\left( W\cdot m^{-2}/10a \right) $', ' trend$\left( W\cdot m^{-2}/10a \right) $', ' trend$\left( W\cdot m^{-2}/10a \right) $', ...
                ' trend$\left( W\cdot m^{-2}/10a \right) $', ' trend$\left( W\cdot m^{-2}/10a \right) $', ' trend$\left( W\cdot m^{-2}/10a \right) $'};
            mlabels.component = {'Ts radEffect', 'TOA net Flux', 'RHeating(sfc)', ...
                'Ta radEffect', 'Ts radEffect', 'Ts radEffect ', ...
                'Ts Effect on atmos', 'Ta+q+Alb+Cloud radEffect', 'Kernel Residual', ...
                'Cloud radEffect', 'q radEffect', 'Albedo radEffect'}; %4*3
            mlabels.componentNames = {'dRtoa_ts', 'dnetTOA', 'drhs', ...
                'dRtoa_ta', 'dRtoa_ts', 'dRtoa_ts', ...
                'dRatm_tsAtom', 'dRtoa_mainEffect', 'dRtoa_residual', ...
                'dRtoa_cloud', 'dRtoa_q', 'dRtoa_alb', 'dRtoa_ts'};
            mlabels.vars = strcat('trendyr_', mlabels.componentNames);
            mlabels.level = level_label{p_1};
        elseif strcmp(p_3, 'nonLocalCld_rad') == 1
            p_1 = 2;
            %% specific labels
            mlabels.unite = {' trend$\left( W\cdot m^{-2}/10a \right) $', ' trend$\left( W\cdot m^{-2}/10a \right) $', ' trend$\left( W\cdot m^{-2}/10a \right) $', ...
                ' trend$\left( W\cdot m^{-2}/10a \right) $', ' trend$\left( W\cdot m^{-2}/10a \right) $', ' trend$\left( W\cdot m^{-2}/10a \right) $', ...
                ' trend$\left( W\cdot m^{-2}/10a \right) $', ' trend$\left( W\cdot m^{-2}/10a \right) $', ' trend$\left( W\cdot m^{-2}/10a \right) $', ...
                ' trend$\left( W\cdot m^{-2}/10a \right) $', ' trend$\left( W\cdot m^{-2}/10a \right) $', ' trend$\left( W\cdot m^{-2}/10a \right) $'};
            mlabels.component = {'Ts radEffect', 'TOA net Flux', 'RHeating(sfc)', ...
                'Cloud radEffect', 'non-local cloud radEffect', '$k2\cdot \frac{\partial R}{\partial Tsg}$', ...
                'cloud+non-local cloud radEffect', 'cloud+non-local cloud+$k2\cdot \frac{\partial R}{\partial Tsg}$ radEffect', 'Ta+q+Alb+Cloud radEffect', ...
                'Ta radEffect', 'q radEffect', 'Albedo radEffect'}; %4*3
            mlabels.componentNames = {'dRtoa_ts', 'dnetTOA', 'drhs', ...
                'dRtoa_cloud', 'dRnonLocalCld', 'dRk2', ...
                'dRsumNonlocalCld', 'dRsumNonlocalCldK2', 'dRtoa_mainEffect', ...
                'dRtoa_ta', 'dRtoa_q', 'dRtoa_alb'};
            mlabels.vars = strcat('trendyr_', mlabels.componentNames);
            mlabels.level = level_label{p_1};
        elseif strcmp(p_3, 'nonLocalCld_Ts') == 1
            p_1 = 2;
            %% specific labels
            mlabels.unite = {' trend(K/10a)', ' trend$\left( W\cdot m^{-2}/10a \right) $', ' trend$\left( W\cdot m^{-2}/10a \right) $', ...
                ' trend(K/10a)', ' trend(K/10a)', ' trend(K/10a)', ...
                ' trend(K/10a)', ' trend(K/10a)', ' trend(K/10a)', ...
                ' trend(K/10a)', ' trend(K/10a)', ' trend(K/10a)'};
            mlabels.component = {'Ts', 'TOA net Flux', 'RHeating(sfc)', ...
                'Cloud TsEffect', 'non-local cloud TsEffect', '$k2\cdot \frac{\partial R}{\partial Tsg}$ TsEffect', ...
                'cloud+non-local cloud TsEffect', 'cloud+non-local cloud+$k2\cdot \frac{\partial R}{\partial Tsg}$ TsEffect', 'Ta+q+Alb+Cloud TsEffect', ...
                'Ta TsEffect', 'q TsEffect', 'Albedo TsEffect'}; %4*3
            mlabels.componentNames = {'dts', 'dnetTOA', 'drhs', ...
                'dTs_cld', 'dTsnonLocalCld', 'dTsk2', ...
                'dTssumNonlocalCld', 'dTssumNonlocalCldK2', 'dTs_mainEffect', ...
                'dTs_ta', 'dTs_hus', 'dTs_alb'};
            mlabels.vars = strcat('trendyr_', mlabels.componentNames);
            mlabels.level = level_label{p_1};

        end

    elseif mean(p_1 == 1) == 1 || strcmp(p_1, 'SFC') == 1 || strcmp(p_1, 'sfc') == 1

        if strcmp(p_3, 'radEffect') == 1
            p_1 = 1;
            %% specific labels
            mlabels.unite = {' trend$\left( W\cdot m^{-2}/10a \right) $', ' trend$\left( W\cdot m^{-2}/10a \right) $', ' trend$\left( W\cdot m^{-2}/10a \right) $', ...
                ' trend$\left( W\cdot m^{-2}/10a \right) $', ' trend$\left( W\cdot m^{-2}/10a \right) $', ' trend$\left( W\cdot m^{-2}/10a \right) $', ...
                ' trend$\left( W\cdot m^{-2}/10a \right) $', ' trend$\left( W\cdot m^{-2}/10a \right) $', ' trend$\left( W\cdot m^{-2}/10a \right) $', ...
                ' trend$\left( W\cdot m^{-2}/10a \right) $', ' trend$\left( W\cdot m^{-2}/10a \right) $', ' trend$\left( W\cdot m^{-2}/10a \right) $'};
            mlabels.component = {'Ts radEffect', 'RHeating include LH+SH', 'RHeating(sfc)', ...
                'Ta radEffect', 'Ta radEffect(near sfc)', 'Ta radEffect(without near sfc) ', ...
                'Ts Effect on atmos', 'Ta+q+Alb+Cloud radEffect', 'Kernel Residual', ...
                'Cloud radEffect', 'q radEffect', 'Albedo radEffect'}; %4*3
            mlabels.componentNames = {'dRsfc_ts', 'drhsPlus', 'drhs', ...
                'dRsfc_ta', 'dRsfc_tas2', 'dRsfc_taOnly2', ...
                'dRatm_tsAtom', 'dRsfc_mainEffect', 'dRsfc_residual', ...
                'dRsfc_cloud', 'dRsfc_q', 'dRsfc_alb', 'dRsfc_ts'};
            mlabels.vars = strcat('trendyr_', mlabels.componentNames);
            mlabels.level = level_label{p_1};
        elseif strcmp(p_3, 'nonLocalCld_rad') == 1
            p_1 = 1;
            %% specific labels
            mlabels.unite = {' trend$\left( W\cdot m^{-2}/10a \right) $', ' trend$\left( W\cdot m^{-2}/10a \right) $', ' trend$\left( W\cdot m^{-2}/10a \right) $', ...
                ' trend$\left( W\cdot m^{-2}/10a \right) $', ' trend$\left( W\cdot m^{-2}/10a \right) $', ' trend$\left( W\cdot m^{-2}/10a \right) $', ...
                ' trend$\left( W\cdot m^{-2}/10a \right) $', ' trend$\left( W\cdot m^{-2}/10a \right) $', ' trend$\left( W\cdot m^{-2}/10a \right) $', ...
                ' trend$\left( W\cdot m^{-2}/10a \right) $', ' trend$\left( W\cdot m^{-2}/10a \right) $', ' trend$\left( W\cdot m^{-2}/10a \right) $'};
            mlabels.component = {'Ts radEffect', 'RHeating include LH+SH', 'RHeating(sfc)', ...
                'Cloud radEffect', 'non-local cloud radEffect', '$k2\cdot \frac{\partial R}{\partial Tsg}$', ...
                'cloud+non-local cloud radEffect', 'cloud+non-local cloud+$k2\cdot \frac{\partial R}{\partial Tsg}$ radEffect', 'Ta+q+Alb+Cloud radEffect', ...
                'Ta radEffect', 'q radEffect', 'Albedo radEffect'}; %4*3
            mlabels.componentNames = {'dRsfc_ts', 'drhsPlus', 'drhs', ...
                'dRsfc_cloud', 'dRnonLocalCld', 'dRk2', ...
                'dRsumNonlocalCld', 'dRsumNonlocalCldK2', 'dRsfc_mainEffect', ...
                'dRsfc_ta', 'dRsfc_q', 'dRsfc_alb'};
            mlabels.vars = strcat('trendyr_', mlabels.componentNames);
            mlabels.level = level_label{p_1};
        elseif strcmp(p_3, 'nonLocalCld_Ts') == 1
            p_1 = 1;
            %% specific labels
            mlabels.unite = {' trend(K/10a)', ' trend$\left( W\cdot m^{-2}/10a \right) $', ' trend$\left( W\cdot m^{-2}/10a \right) $', ...
                ' trend(K/10a)', ' trend(K/10a)', ' trend(K/10a)', ...
                ' trend(K/10a)', ' trend(K/10a)', ' trend(K/10a)', ...
                ' trend(K/10a)', ' trend(K/10a)', ' trend(K/10a)'};
            mlabels.component = {'Ts', 'RHeating include LH+SH', 'RHeating(sfc)', ...
                'Cloud TsEffect', 'non-local cloud TsEffect', '$k2\cdot \frac{\partial R}{\partial Tsg}$ TsEffect', ...
                'cloud+non-local cloud TsEffect', 'cloud+non-local cloud+$k2\cdot \frac{\partial R}{\partial Tsg}$ TsEffect', 'Ta+q+Alb+Cloud TsEffect', ...
                'Ta TsEffect', 'q TsEffect', 'Albedo TsEffect'}; %4*3
            mlabels.componentNames = {'dts', 'drhsPlus', 'drhs', ...
                'dTs_cld', 'dTsnonLocalCld', 'dTsk2', ...
                'dTssumNonlocalCld', 'dTssumNonlocalCldK2', 'dTs_mainEffect', ...
                'dTs_ta', 'dTs_hus', 'dTs_alb'};
            mlabels.vars = strcat('trendyr_', mlabels.componentNames);
            mlabels.level = level_label{p_1};
        elseif strcmp(p_3, 'nonLocalCld2') == 1
            p_1 = 1;
            %% specific labels
            mlabels.unite = {' trend(K/10a)', ' trend$\left( W\cdot m^{-2}/10a \right) $', ' trend(K/10a)', ...
                ' trend(K/10a)', ' trend(K/10a)', ' trend(K/10a)', ...
                ' trend$\left( W\cdot m^{-2}/10a \right) $', ' trend$\left( W\cdot m^{-2}/10a \right) $', ' trend$\left( W\cdot m^{-2}/10a \right) $', ...
                ' trend(K/10a)', ' trend(K/10a)', ' trend(K/10a)'};
            mlabels.component = {'Ts', 'RHeating(sfc)', 'Ta+q+Alb+Cloud TsEffect', ...
                'Cloud TsEffect', 'non-local cloud TsEffect', 'cloud+non-local cloud TsEffect', ...
                'Cloud radEffect', 'non-local cloud radEffect', 'cloud+non-local cloud radEffect',  ...
                'Ta TsEffect', 'q TsEffect', 'Albedo TsEffect'}; %4*3
            mlabels.componentNames = {'dts', 'drhs', 'dTs_mainEffect', ...
                'dTs_cld', 'dTsnonLocalCld2', 'dTssumNonlocalCld2', ...
                'dRsfc_cloud', 'dRnonLocalCld2', 'dRsumNonlocalCld2', ...
                'dTs_ta', 'dTs_hus', 'dTs_alb'};
            mlabels.vars = strcat('trendyr_', mlabels.componentNames);
            mlabels.level = level_label{p_1};

        end

    end

    if mean(p_2 == 0) == 1 || strcmp(p_2, 'land sea') == 1 || strcmp(p_2, 'landSea') == 1 || strcmp(p_2, 'landsea') == 1
        areaNum = 0;
        mlabels.area = 'landSea';
    elseif mean(p_2 == 1) == 1 || strcmp(p_2, 'land') == 1
        areaNum = 1;
        mlabels.area = 'land';
    elseif mean(p_2 == 2) == 1 || strcmp(p_2, 'china') == 1
        areaNum = 2;
        mlabels.area = 'china';
    end

    mlabels.fileN1 = strcat(mlabels.area, '_', p_3);

end
